#!/bin/bash
# Create lookup file to dotfile root
if [ ! -d "$HOME/.dotfile.config" ]; then
    ln -rsf . "$HOME/.dotfile.config"
fi
for script in $(find ./*/ -name setup); do
    pushd $(dirname $script)
    echo "$script"
    . setup
    #. "$script"
    # $(setup)
    popd
done

#$(find . -name setup)
