#!/bin/bash
VIMRC=$(dirname "$(realpath -s "$0")")/vimrc
VIMDIR=$(dirname "$(realpath -s "$0")")/vim
ln -rsf "$VIMRC" ~/.vimrc
if [ -d "$VIMDIR"  ] && [ ! -L "$VIMDIR" ]; then
    rm -rf ~/.vim
fi
ln -rsf -- "$VIMDIR" ~/.vim
