#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# set PATH so it includes user's private bin directories
export PATH=".:$HOME/bin:$PATH:$HOME/.local/bin:$HOME/.npm-global/bin:./node_modules/.bin:/usr/local/go/bin:$HOME/go/bin"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    ## include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

export FORMAT="\nID\t{{.ID}}\nIMAGE\t{{.Image}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.RunningFor}}\nSTATUS\t{{.Status}}\nPORTS\t{{.Ports}}\nNAMES\t{{.Names}}\n"

export EDITOR="/snap/bin/nvim"

function docker_conn() {
    docker exec -it $1 bash
}

alias dps='docker ps --format=$FORMAT'
alias dconn='docker_conn $1'

function pd() {
    if [ "$1" = "" ]; then
        popd
    else
        pushd $1
    fi
}

if [ -f "$HOME/bin/.init.sh" ]; then
    pushd "$HOME/bin" >/dev/null && source ".init.sh"
    popd >/dev/null
else
    echo 'cd && git clone git@github.com:garrett-is-a-swann/bin.git'
fi
